INSERT INTO public.team (id, name, clubid, leagueid) VALUES (2, 'Termite Chevalierberg 2', 1, 1);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (3, 'Seahorse North Tracetown 1', 2, 1);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (4, 'Bat Aliyahport 1', 3, 1);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (5, 'Sparrow South Matilde 1', 4, 1);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (6, 'Hummingbird North Mckaylamouth 1', 5, 1);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (7, 'Eel Lake Zachery 1', 6, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (8, 'Sand Dollar Port Zionmouth 1', 7, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (9, 'Meerkat New Audreanneville 1', 8, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (10, 'Ant North Brooksbury 1', 9, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (11, 'Coyote Karleystad 1', 10, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (12, 'Chough East Alf 1', 11, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (13, 'Rook Port Jaimefort 1', 12, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (14, 'Cheetah Morinshire 1', 13, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (15, 'Crane North Nelda 1', 14, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (16, 'Lyrebird Lake Dorianfort 1', 15, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (17, 'Sand Dollar Lillianchester 1', 16, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (18, 'Swallow Garryshire 1', 17, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (19, 'Louse Hellenville 1', 18, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (20, 'Goat Lake Ashley 1', 19, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (21, 'Hippopotamus Port Stephanymouth 1', 20, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (22, 'Chicken Domenicaland 1', 21, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (23, 'Parrot West Sylvester 1', 22, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (24, 'Llama Lamberthaven 1', 23, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (25, 'Peafowl Fabrebury 1', 24, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (26, 'Giraffe Lake Ernesto 1', 25, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (27, 'Woodpecker Dumontchester 1', 26, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (28, 'Turkey West Billiefurt 1', 27, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (29, 'Woodcock Isaiahside 1', 28, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (30, 'Goshawk East Rosella 1', 29, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (31, 'Porcupine West Bulahchester 1', 30, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (32, 'Hamster North Augustine 1', 31, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (33, 'Capybara West Hopeland 1', 32, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (34, 'Nightingale Port Fionaton 1', 33, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (35, 'Barracuda Renaudton 1', 34, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (36, 'Ram North Oscar 1', 35, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (37, 'Lapwing New Brooklyn 1', 36, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (38, 'Wildcat Rubiehaven 1', 37, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (39, 'Barracuda South Yasmine 1', 38, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (40, 'Dugong South Lorenzotown 1', 39, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (41, 'Dinosaur Billchester 1', 40, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (42, 'Baboon West Fayeton 1', 41, 6);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (43, 'Antelope East Valentine 1', 42, 6);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (44, 'Hare Rocheland 1', 43, 6);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (45, 'Capybara Lake Chelseaview 1', 44, 6);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (46, 'Lemur Humbertotown 1', 45, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (47, 'Kouprey Roberttown 1', 46, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (48, 'Turkey South Ashly 1', 47, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (49, 'Panther Dumontside 1', 48, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (50, 'Reindeer Lake Lauren', 49, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (51, 'Red panda North Myriamland 1', 50, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (52, 'Pheasant East Rodrigoside 1', 51, 7);