INSERT INTO public.stadium (id, name, address, capacity) VALUES (201, 'Malibu stadium', 'South Francescoview, 5819 Pons Laffitte', 36024);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (202, 'Ranchero stadium', 'Fernandoside, 516 Bonnet du Bac', 10762);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (203, 'Golf stadium', 'Le gallview, 6690 Lucienne de l''Abbaye', 54355);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (204, 'A8 stadium', 'Port Micheleland, 69216 Shanie de Caumartin', 88948);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (205, 'Impala stadium', 'New Daphneside, 75871 Magdalen des Saussaies', 36041);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (206, 'Model 3 stadium', 'Noelfurt, 78883 Perrin des Lombards', 57266);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (207, 'Mercielago stadium', 'South Toreyburgh, 586 Meunier d''Argenteuil', 33130);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (208, 'Ranchero stadium', 'Brittanymouth, 9164 Nicolas du Dahomey', 9180);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (209, 'Accord stadium', 'New Marty, 72939 Irving d''Assas', 24689);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (210, 'Impala stadium', 'Lake Elenoraberg, 74377 Bonnet Laffitte', 62092);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (211, 'PT Cruiser stadium', 'Lemairebury, 077 Fleury Delesseux', 67722);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (212, 'Explorer stadium', 'New Emilianostad, 399 Eileen des Lombards', 98454);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (213, 'Mercielago stadium', 'East Keanushire, 180 Jamar des Lombards', 71261);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (214, 'Civic stadium', 'Rousseaustad, 6001 Marty Delesseux', 70922);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (215, 'Fiesta stadium', 'South Kolbyhaven, 627 Pierre de Tilsitt', 61879);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (216, 'Expedition stadium', 'West Helena, 611 Jacquet de Presbourg', 75697);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (217, 'Civic stadium', 'West Dougstad, 5354 Fritz Charlemagne', 61127);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (218, 'Impala stadium', 'South Ciceromouth, 67327 Domingo Joubert', 71547);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (219, 'Charger stadium', 'New Carolineton, 6702 Richard d''Abbeville', 38734);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (220, 'Model T stadium', 'Blancfurt, 35794 Vidal de Nesle', 13723);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (221, 'Model S stadium', 'New Favianton, 17473 Fiona de Paris', 726);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (222, 'Model S stadium', 'South Chelsea, 6129 Felicita Royale', 29882);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (223, 'F-150 stadium', 'Constantinmouth, 00873 Boyer de Richelieu', 42172);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (224, 'Model T stadium', 'Port Miracle, 2714 Vivianne des Panoramas', 26311);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (225, 'Focus stadium', 'East Amina, 046 Guillaume des Rosiers', 78453);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (226, 'Roadster stadium', 'Baileyside, 8333 Huet d''Orsel', 83580);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (227, 'LeBaron stadium', 'Lake Oscar, 8603 Myrl des Lombards', 79073);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (228, 'Impala stadium', 'Olivierburgh, 557 Jean de Richelieu', 80513);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (229, 'XTS stadium', 'North Chasefort, 005 Dubois Saint-Honoré', 83418);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (230, 'ATS stadium', 'Port Mariloustad, 33940 Vasseur de Montmorency', 45092);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (231, 'Grand Cherokee stadium', 'New Cletus, 8818 Hubert du Chat-qui-Pêche', 86537);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (232, 'Countach stadium', 'North Bonitaview, 3815 Prevost d''Argenteuil', 60233);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (233, 'El Camino stadium', 'Rubyville, 49450 Dorothea de la Chaussée-d''Antin', 46375);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (234, 'El Camino stadium', 'Durandmouth, 10426 Raphael d''Abbeville', 56220);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (235, 'Alpine stadium', 'Percyside, 41449 Fernandez de l''Abbaye', 61303);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (236, 'F-150 stadium', 'Cloydside, 64679 Brunet de la Huchette', 69271);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (237, 'Element stadium', 'Port Friedrichfurt, 46609 Boyer de Paris', 14924);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (238, 'Model 3 stadium', 'Vladimirchester, 812 Gerard Saint-Bernard', 73271);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (239, 'Model 3 stadium', 'New Donavon, 207 Furman d''Argenteuil', 20237);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (240, 'Taurus stadium', 'New Makaylaton, 5954 Zena du Bac', 40014);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (241, 'Grand Cherokee stadium', 'West Randal, 7459 Mable Saint-Séverin', 64343);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (242, 'Civic stadium', 'Gautiermouth, 65217 Sanchez de Paris', 432);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (243, 'Malibu stadium', 'Fleuryfurt, 253 Lemaire du Chat-qui-Pêche', 30546);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (244, 'Ranchero stadium', 'Port Noemimouth, 4925 Bourgeois Molière', 8438);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (245, 'Charger stadium', 'Nicolasstad, 285 Ernestina Saint-Honoré', 40169);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (246, 'Volt stadium', 'West Jessica, 6816 Deschamps Dauphine', 35596);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (247, 'Altima stadium', 'West Ward, 2869 D''angelo de la Huchette', 39658);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (248, '911 stadium', 'Lake Travisport, 22200 Karine Montorgueil', 36106);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (249, 'Prius stadium', 'Francoisshire, 2392 Mortimer de Seine', 14285);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (250, 'Sentra stadium', 'South Jovani, 61069 Savanah de la Huchette', 18896);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (251, 'Corvette stadium', 'North Tobinville, 8561 Melissa Monsieur-le-Prince', 52195);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (252, 'A8 stadium', 'Nicolaville, 84249 Minnie du Bac', 2697);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (253, 'Altima stadium', 'Vidalville, 0861 Petit de Rivoli', 29047);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (254, 'Model S stadium', 'West Kenyatta, 19293 Orie Molière', 68803);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (255, 'Altima stadium', 'New Elouiseville, 9483 Leclerc de la Pompe', 91270);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (256, 'Accord stadium', 'East Geoffreyshire, 160 Dumont de Tilsitt', 46017);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (257, 'CTS stadium', 'South Linneashire, 00752 Jena Lepic', 74262);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (258, 'Grand Caravan stadium', 'Victoriamouth, 51717 Patricia Saint-Dominique', 13658);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (259, 'Model 3 stadium', 'New Corrineburgh, 9228 Arnaud de l''Odéon', 67226);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (260, 'A8 stadium', 'Keatonmouth, 68686 Kristin Mouffetard', 53258);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (261, 'Charger stadium', 'West Vivienne, 6082 Leclercq d''Alésia', 1861);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (262, 'Charger stadium', 'Lake Peterton, 41746 Rey Pierre Charron', 6646);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (263, 'Prius stadium', 'Lake Elmirafort, 843 Gavin de la Bûcherie', 71392);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (264, 'Element stadium', 'South Jarrod, 268 Pearl de Rivoli', 63247);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (265, 'A8 stadium', 'New Neil, 0555 Kellen de Tilsitt', 3976);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (266, 'Cruze stadium', 'Leonefort, 721 Imelda du Faubourg-Saint-Denis', 75228);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (267, 'PT Cruiser stadium', 'West Thurman, 504 Lemaire Molière', 47559);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (268, 'Camaro stadium', 'North Rettaland, 5805 Dumas d''Assas', 46286);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (269, 'Land Cruiser stadium', 'East Alexzander, 14045 Emily du Bac', 3407);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (270, 'Grand Caravan stadium', 'North Stephanieville, 50203 Renard Zadkine', 80637);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (271, 'Civic stadium', 'Dumasfurt, 895 Roy Mouffetard', 2437);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (272, 'Mustang stadium', 'East Mattie, 44582 Poirier Saint-Séverin', 77012);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (273, 'PT Cruiser stadium', 'South Gregorio, 68424 David de Vaugirard', 20171);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (274, 'Taurus stadium', 'Gautierbury, 2153 Laine de la Pompe', 85530);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (275, 'Explorer stadium', 'North Morrisburgh, 8311 Marie d''Abbeville', 24032);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (276, 'Cruze stadium', 'Remybury, 3351 Fontaine Saint-Honoré', 52067);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (277, 'Land Cruiser stadium', 'Andrewtown, 3822 Quentin de la Chaussée-d''Antin', 39159);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (278, 'Altima stadium', 'Dupuisberg, 98850 Benoit de la Paix', 86955);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (279, 'Durango stadium', 'Jeanborough, 37222 Jaylan Saint-Honoré', 11077);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (280, 'Corvette stadium', 'Bernieceton, 29357 Andrew Royale', 9111);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (281, 'Altima stadium', 'Marchandmouth, 6760 Mortimer Saint-Dominique', 95598);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (282, 'Accord stadium', 'North Raheem, 4535 Nicolas de Richelieu', 27481);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (283, 'Colorado stadium', 'Guillaumemouth, 378 Renard Charlemagne', 52506);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (284, 'PT Cruiser stadium', 'East Paolo, 580 Huet de Solférino', 92088);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (285, 'Accord stadium', 'West Nellieshire, 48487 Rodriguez Pastourelle', 76722);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (286, 'Camry stadium', 'Olivierville, 743 Olivier des Grands Augustins', 72922);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (287, 'Challenger stadium', 'Lake Cynthia, 76430 Cortez de Rivoli', 73700);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (288, 'Cruze stadium', 'Bridieland, 185 Michel du Faubourg-Saint-Denis', 81225);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (289, 'Roadster stadium', 'South Casimer, 295 Elvis d''Orsel', 65451);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (290, 'Ranchero stadium', 'New Mabel, 1142 Joseph Mouffetard', 86839);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (291, 'Countach stadium', 'Renardberg, 40352 Mathieu Royale', 35076);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (292, 'Wrangler stadium', 'Lake Gersonberg, 765 Adam du Faubourg-Saint-Denis', 87222);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (293, 'Escalade stadium', 'Quincyberg, 309 Perrin Saint-Dominique', 38555);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (294, 'Focus stadium', 'Lake Jerry, 372 Fleury de Richelieu', 18185);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (295, 'Model T stadium', 'Bertrandberg, 622 Lambert du Faubourg Saint-Honoré', 55789);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (296, 'Impala stadium', 'South Lacymouth, 919 Sanchez de la Victoire', 76296);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (297, 'F-150 stadium', 'Picardbury, 030 Sanchez Saint-Honoré', 27805);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (298, 'F-150 stadium', 'Bonnettown, 1402 Augustus Royale', 77935);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (299, 'A8 stadium', 'Blanchaven, 14287 Elias Saint-Dominique', 35715);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (300, 'Charger stadium', 'Colinmouth, 98245 Le gall de Solférino', 57952);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (301, 'A8 stadium', 'Louistown, 927 Aiyana de Vaugirard', 99973);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (302, 'Model T stadium', 'Kristianberg, 601 Wyman Joubert', 49636);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (303, 'Colorado stadium', 'New Nyahborough, 419 Vincent Laffitte', 33422);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (304, 'Model T stadium', 'New Carmenton, 6997 Louie de Nesle', 9664);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (305, 'Durango stadium', 'Chadrickland, 90103 Winona du Faubourg Saint-Honoré', 30622);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (306, 'Wrangler stadium', 'East Mervin, 07515 Rolland Charlemagne', 49922);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (307, 'Land Cruiser stadium', 'West Cathrine, 475 Dupont La Boétie', 88109);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (308, 'Golf stadium', 'Huetside, 2384 Lon Monsieur-le-Prince', 86948);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (309, 'Colorado stadium', 'Deontechester, 7218 Cornell de Paris', 14186);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (310, 'Camry stadium', 'Winifredchester, 74131 Elissa de Tilsitt', 57718);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (311, 'Cruze stadium', 'Sabrynahaven, 115 Kaylie Saint-Honoré', 70114);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (312, 'Mustang stadium', 'Sunnymouth, 131 Huet Joubert', 36061);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (313, 'Camaro stadium', 'North Dixie, 97139 Lucio des Saussaies', 78289);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (314, 'Golf stadium', 'Haroldbury, 39478 Bonnet Mouffetard', 37372);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (315, 'Ranchero stadium', 'Bryceside, 6636 Percival Vaneau', 2570);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (316, 'CTS stadium', 'North Kailynton, 58041 Laurent Charlemagne', 85686);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (317, 'XTS stadium', 'Lake Antwonbury, 4483 Ross de Rivoli', 93773);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (318, 'Civic stadium', 'Lamontton, 8737 Nella Royale', 94906);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (319, 'Jetta stadium', 'New Londonport, 5178 Renault Joubert', 82677);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (320, 'Jetta stadium', 'Port Russelchester, 8400 Louis Du Sommerard', 34017);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (321, 'Mustang stadium', 'South Reyes, 529 Da silva du Faubourg-Saint-Denis', 38637);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (322, 'Accord stadium', 'New Christop, 056 Meggie de Nesle', 37962);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (323, 'Malibu stadium', 'Gautierville, 03699 Marie Vaneau', 74416);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (324, 'Altima stadium', 'Tabithaside, 55943 Lucas Zadkine', 10313);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (325, 'Challenger stadium', 'Zionhaven, 84466 Paul Charlemagne', 44766);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (326, 'Land Cruiser stadium', 'North Maegan, 6492 Lowell Saint-Séverin', 93595);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (327, 'Focus stadium', 'Lake Cortney, 63706 Le gall de Caumartin', 96551);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (328, 'Durango stadium', 'Lake Gregoriaborough, 10502 Chase de Seine', 86675);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (329, 'Impala stadium', 'Le gallbury, 54464 Justine des Saussaies', 81070);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (330, 'Jetta stadium', 'Port Erna, 32482 Eulalia Adolphe Mille', 51141);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (331, 'Roadster stadium', 'New Juliannestad, 0008 Gauthier Saint-Jacques', 56626);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (332, 'A8 stadium', 'West Justonhaven, 335 Berger de Nesle', 17695);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (333, 'ATS stadium', 'Port Maidachester, 828 Roux Oberkampf', 79358);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (334, 'Cruze stadium', 'Port Aracelyhaven, 784 Wade des Lombards', 25173);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (335, 'Cruze stadium', 'North Olinland, 76579 Deven Mouffetard', 96901);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (336, 'Civic stadium', 'Nickolastown, 24235 Haven de l''Odéon', 31526);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (337, 'Altima stadium', 'Davontehaven, 674 Bailee de Seine', 7121);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (338, 'Impala stadium', 'North Crystelland, 92989 Louis Joubert', 56595);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (339, 'A8 stadium', 'West David, 3155 Moreau de la Pompe', 12863);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (340, 'Alpine stadium', 'East Elroyland, 328 Sanchez Vaneau', 92194);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (341, 'Spyder stadium', 'Poirierhaven, 2837 Annetta Du Sommerard', 20327);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (342, 'Mustang stadium', 'Lefevreport, 43442 Riviere Mouffetard', 35962);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (343, 'Element stadium', 'Port Felicity, 64371 Roger Marcadet', 79814);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (344, 'Grand Cherokee stadium', 'West Sheridanburgh, 2714 Marcelo Dauphine', 75928);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (345, 'Model S stadium', 'North Adolphusview, 80374 Foster Lepic', 62242);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (346, 'Explorer stadium', 'New Herbert, 477 Meyer Dauphine', 42193);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (347, 'Countach stadium', 'Pollychester, 34836 Vivian d''Orsel', 80629);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (348, 'Explorer stadium', 'Mullerberg, 139 Da silva de la Chaussée-d''Antin', 80430);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (349, 'ATS stadium', 'Lake Alejandrin, 921 Pons Charlemagne', 69382);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (350, 'Altima stadium', 'Shyanneberg, 467 Fleury Dauphine', 40971);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (351, 'Mustang stadium', 'North Chasityland, 82299 Myron d''Alésia', 46098);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (352, 'Grand Caravan stadium', 'West Eltonfort, 904 Bertrand Pastourelle', 35718);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (353, 'Impala stadium', 'Port Urban, 104 Hollis d''Abbeville', 15360);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (354, 'Challenger stadium', 'Arnaudchester, 62959 Kory de la Huchette', 64434);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (355, 'Jetta stadium', 'Zacharybury, 104 Maillard de Vaugirard', 60663);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (356, 'A8 stadium', 'Margaretttown, 0496 Nicolas des Francs-Bourgeois', 88309);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (357, 'El Camino stadium', 'North Catherineborough, 755 Antonina Montorgueil', 61906);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (358, 'Fiesta stadium', 'East Robbie, 0316 Novella de Vaugirard', 39922);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (359, 'Charger stadium', 'North Reeceland, 360 Zachary Saint-Séverin', 73614);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (360, 'Camaro stadium', 'Laurentport, 22730 Baron de la Huchette', 54883);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (361, 'Explorer stadium', 'Lake Daytonport, 1431 Prevost Saint-Bernard', 55358);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (362, 'Taurus stadium', 'West Ryleighton, 1801 Myrl de Nesle', 15098);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (363, 'Countach stadium', 'West Lawrencemouth, 8416 Laine de Caumartin', 73567);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (364, 'Impala stadium', 'West Kingtown, 779 Fleury Vaneau', 47807);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (365, 'Model T stadium', 'Thomaschester, 35152 Adam de Solférino', 53596);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (366, 'Grand Cherokee stadium', 'Lake Orenville, 61713 Lambert des Rosiers', 70830);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (367, 'A4 stadium', 'East Aricland, 394 Renard de la Pompe', 61312);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (368, 'Escalade stadium', 'South Gregoriochester, 429 Jon des Lombards', 48803);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (369, 'Countach stadium', 'New Lavern, 3562 Kacey de Seine', 30484);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (370, 'CTS stadium', 'East Saige, 01484 Andre de l''Abbaye', 38755);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (371, 'Impala stadium', 'West Ianfurt, 0334 Garcia des Saussaies', 35875);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (372, 'Model T stadium', 'New Natshire, 597 Alyson Dauphine', 2562);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (373, 'Impala stadium', 'Emmanuelleport, 78736 Gwendolyn du Dahomey', 85922);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (374, 'F-150 stadium', 'Rivierestad, 5302 Lacroix de l''Abbaye', 54341);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (375, 'Expedition stadium', 'North Colemanport, 47410 Tyrese du Havre', 93393);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (376, 'F-150 stadium', 'Royburgh, 6281 Julien de Vaugirard', 40945);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (377, 'Ranchero stadium', 'Zoeybury, 2461 Sanchez du Dahomey', 37161);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (378, 'A4 stadium', 'East Desmondfort, 841 Robin de la Victoire', 77875);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (379, 'Element stadium', 'Port Jonathonville, 690 Thomas de Tilsitt', 91052);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (380, 'A4 stadium', 'North Melba, 102 Gerard Monsieur-le-Prince', 76478);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (381, 'Beetle stadium', 'New Judy, 4935 Jesus de la Paix', 22432);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (382, 'Prius stadium', 'Kyleeview, 104 Rolland Saint-Bernard', 93676);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (383, 'Focus stadium', 'Andrebury, 1458 Guillot Marcadet', 12866);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (384, 'Grand Cherokee stadium', 'Andrefurt, 063 Catharine d''Argenteuil', 71251);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (385, 'Taurus stadium', 'South Eldred, 46921 Petit de la Paix', 15945);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (386, 'Model T stadium', 'South Marco, 82370 Eudora de la Paix', 81939);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (387, 'Expedition stadium', 'Lake Vickie, 507 Thomas des Panoramas', 226);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (388, 'Roadster stadium', 'Port Madisenville, 0733 Damien Mouffetard', 24401);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (389, 'Corvette stadium', 'New Sandra, 360 Guerin de la Bûcherie', 47099);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (390, 'Explorer stadium', 'Obiehaven, 9340 Martin d''Alésia', 73114);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (391, 'Roadster stadium', 'Lake Alekport, 08668 Emanuel de Tilsitt', 44492);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (392, 'A4 stadium', 'Reyside, 322 Cecile Monsieur-le-Prince', 4648);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (393, 'ATS stadium', 'Blancburgh, 742 Tabitha des Rosiers', 23707);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (394, 'PT Cruiser stadium', 'West Imani, 0622 Federico La Boétie', 78404);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (395, 'Model 3 stadium', 'North Richmond, 542 Carre du Dahomey', 72835);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (396, 'Element stadium', 'Lillieside, 309 Marchal Molière', 44170);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (397, 'Camry stadium', 'New Clydeton, 3691 Vasseur Lepic', 9592);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (398, 'Durango stadium', 'East Eleonore, 985 Francois Saint-Denis', 259);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (399, 'Colorado stadium', 'Giraudton, 115 Picard de Richelieu', 9204);
INSERT INTO public.stadium (id, name, address, capacity) VALUES (400, 'Wrangler stadium', 'Parishaven, 6862 Elsie du Chat-qui-Pêche', 96103);