INSERT INTO public.league (id, level, gender) VALUES (3, 'Liga Invernal Veracruzana', 'F', 1);
INSERT INTO public.league (id, level, gender) VALUES (4, 'Arizona Fall League', 'F', 2);
INSERT INTO public.league (id, level, gender) VALUES (1, 'Major League', 'M', 3);
INSERT INTO public.league (id, level, gender) VALUES (2, 'China National', 'M', 4);
INSERT INTO public.league (id, level, gender) VALUES (5, 'National League', 'M', 5);
INSERT INTO public.league (id, level, gender) VALUES (6, 'Slovak Extraliga', 'M', 6);
INSERT INTO public.league (id, level, gender) VALUES (7, 'Damettan', 'F', 7);
INSERT INTO public.league (id, level, gender) VALUES (8, 'Chinese New Alliance', 'M', 8);
INSERT INTO public.league (id, level, gender) VALUES (9, 'Liga Pilipinas', 'F', 1);
INSERT INTO public.league (id, level, gender) VALUES (10, 'MNBL', 'F', 2);
INSERT INTO public.league (id, level, gender) VALUES (11, 'NBL League', 'M', 3);
INSERT INTO public.league (id, level, gender) VALUES (12, 'National Alliance League', 'M', 4);
INSERT INTO public.league (id, level, gender) VALUES (13, 'Ghetto Discrict', 'M', 5);
INSERT INTO public.league (id, level, gender) VALUES (14, 'Eastern Pro League', 'M', 6);
INSERT INTO public.league (id, level, gender) VALUES (15, 'Victorian League', 'F', 7);
INSERT INTO public.league (id, level, gender) VALUES (16, 'Kianaland Distric', 'F', 8);
INSERT INTO public.league (id, level, gender) VALUES (17, 'Japan United ', 'M', 1);
INSERT INTO public.league (id, level, gender) VALUES (18, 'Bumbledom Official', 'M', 2);
INSERT INTO public.league (id, level, gender) VALUES (19, 'Joementum League', 'M', 3);