INSERT INTO public.club (id, name, sportid) VALUES (1, 'Termite Chevalierberg', 6);
INSERT INTO public.club (id, name, sportid) VALUES (2, 'Seahorse North Tracetown', 5);
INSERT INTO public.club (id, name, sportid) VALUES (3, 'Bat Aliyahport', 2);
INSERT INTO public.club (id, name, sportid) VALUES (4, 'Sparrow South Matilde', 3);
INSERT INTO public.club (id, name, sportid) VALUES (5, 'Hummingbird North Mckaylamouth', 4);
INSERT INTO public.club (id, name, sportid) VALUES (6, 'Eel Lake Zachery', 3);
INSERT INTO public.club (id, name, sportid) VALUES (7, 'Sand Dollar Port Zionmouth', 5);
INSERT INTO public.club (id, name, sportid) VALUES (8, 'Meerkat New Audreanneville', 3);
INSERT INTO public.club (id, name, sportid) VALUES (9, 'Ant North Brooksbury', 6);
INSERT INTO public.club (id, name, sportid) VALUES (10, 'Coyote Karleystad', 1);
INSERT INTO public.club (id, name, sportid) VALUES (11, 'Chough East Alf', 4);
INSERT INTO public.club (id, name, sportid) VALUES (12, 'Rook Port Jaimefort', 4);
INSERT INTO public.club (id, name, sportid) VALUES (13, 'Cheetah Morinshire', 7);
INSERT INTO public.club (id, name, sportid) VALUES (14, 'Crane North Nelda', 5);
INSERT INTO public.club (id, name, sportid) VALUES (15, 'Lyrebird Lake Dorianfort', 4);
INSERT INTO public.club (id, name, sportid) VALUES (16, 'Sand Dollar Lillianchester', 2);
INSERT INTO public.club (id, name, sportid) VALUES (17, 'Swallow Garryshire', 3);
INSERT INTO public.club (id, name, sportid) VALUES (18, 'Louse Hellenville', 5);
INSERT INTO public.club (id, name, sportid) VALUES (19, 'Goat Lake Ashley', 2);
INSERT INTO public.club (id, name, sportid) VALUES (20, 'Hippopotamus Port Stephanymouth', 5);
INSERT INTO public.club (id, name, sportid) VALUES (21, 'Chicken Domenicaland', 5);
INSERT INTO public.club (id, name, sportid) VALUES (22, 'Parrot West Sylvester', 3);
INSERT INTO public.club (id, name, sportid) VALUES (23, 'Llama Lamberthaven', 5);
INSERT INTO public.club (id, name, sportid) VALUES (24, 'Peafowl Fabrebury', 2);
INSERT INTO public.club (id, name, sportid) VALUES (25, 'Giraffe Lake Ernesto', 2);
INSERT INTO public.club (id, name, sportid) VALUES (26, 'Woodpecker Dumontchester', 1);
INSERT INTO public.club (id, name, sportid) VALUES (27, 'Turkey West Billiefurt', 3);
INSERT INTO public.club (id, name, sportid) VALUES (28, 'Woodcock Isaiahside', 7);
INSERT INTO public.club (id, name, sportid) VALUES (29, 'Goshawk East Rosella', 5);
INSERT INTO public.club (id, name, sportid) VALUES (30, 'Porcupine West Bulahchester', 1);
INSERT INTO public.club (id, name, sportid) VALUES (31, 'Hamster North Augustine', 3);
INSERT INTO public.club (id, name, sportid) VALUES (32, 'Capybara West Hopeland', 6);
INSERT INTO public.club (id, name, sportid) VALUES (33, 'Nightingale Port Fionaton', 5);
INSERT INTO public.club (id, name, sportid) VALUES (34, 'Barracuda Renaudton', 4);
INSERT INTO public.club (id, name, sportid) VALUES (35, 'Ram North Oscar', 4);
INSERT INTO public.club (id, name, sportid) VALUES (36, 'Lapwing New Brooklyn', 2);
INSERT INTO public.club (id, name, sportid) VALUES (37, 'Wildcat Rubiehaven', 1);
INSERT INTO public.club (id, name, sportid) VALUES (38, 'Barracuda South Yasmine', 6);
INSERT INTO public.club (id, name, sportid) VALUES (39, 'Dugong South Lorenzotown', 6);
INSERT INTO public.club (id, name, sportid) VALUES (40, 'Dinosaur Billchester', 7);
INSERT INTO public.club (id, name, sportid) VALUES (41, 'Baboon West Fayeton', 2);
INSERT INTO public.club (id, name, sportid) VALUES (42, 'Antelope East Valentine', 7);
INSERT INTO public.club (id, name, sportid) VALUES (43, 'Hare Rocheland', 3);
INSERT INTO public.club (id, name, sportid) VALUES (44, 'Capybara Lake Chelseaview', 6);
INSERT INTO public.club (id, name, sportid) VALUES (45, 'Lemur Humbertotown', 5);
INSERT INTO public.club (id, name, sportid) VALUES (46, 'Kouprey Roberttown', 7);
INSERT INTO public.club (id, name, sportid) VALUES (47, 'Turkey South Ashly', 5);
INSERT INTO public.club (id, name, sportid) VALUES (48, 'Panther Dumontside', 7);
INSERT INTO public.club (id, name, sportid) VALUES (49, 'Reindeer Lake Lauren', 4);
INSERT INTO public.club (id, name, sportid) VALUES (50, 'Red panda North Myriamland', 5);
INSERT INTO public.club (id, name, sportid) VALUES (51, 'Pheasant East Rodrigoside', 5);