INSERT INTO public.team (id, name, clubid, leagueid) VALUES (2, 'Termite Chevalierberg 2', 1, 1);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (3, 'Seahorse North Tracetown 1', 2, 1);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (4, 'Bat Aliyahport 1', 3, 1);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (5, 'Sparrow South Matilde 1', 4, 1);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (6, 'Hummingbird North Mckaylamouth 1', 5, 1);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (7, 'Eel Lake Zachery 1', 6, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (8, 'Sand Dollar Port Zionmouth 1', 7, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (9, 'Meerkat New Audreanneville 1', 8, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (10, 'Ant North Brooksbury 1', 9, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (11, 'Coyote Karleystad 1', 10, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (12, 'Chough East Alf 1', 11, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (13, 'Rook Port Jaimefort 1', 12, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (14, 'Cheetah Morinshire 1', 13, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (15, 'Crane North Nelda 1', 14, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (16, 'Lyrebird Lake Dorianfort 1', 15, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (17, 'Sand Dollar Lillianchester 1', 16, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (18, 'Swallow Garryshire 1', 17, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (19, 'Louse Hellenville 1', 18, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (20, 'Goat Lake Ashley 1', 19, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (21, 'Hippopotamus Port Stephanymouth 1', 20, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (22, 'Chicken Domenicaland 1', 21, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (23, 'Parrot West Sylvester 1', 22, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (24, 'Llama Lamberthaven 1', 23, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (25, 'Peafowl Fabrebury 1', 24, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (26, 'Giraffe Lake Ernesto 1', 25, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (27, 'Woodpecker Dumontchester 1', 26, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (28, 'Turkey West Billiefurt 1', 27, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (29, 'Woodcock Isaiahside 1', 28, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (30, 'Goshawk East Rosella 1', 29, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (31, 'Porcupine West Bulahchester 1', 30, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (32, 'Hamster North Augustine 1', 31, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (33, 'Capybara West Hopeland 1', 32, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (34, 'Nightingale Port Fionaton 1', 33, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (35, 'Barracuda Renaudton 1', 34, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (36, 'Ram North Oscar 1', 35, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (37, 'Lapwing New Brooklyn 1', 36, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (38, 'Wildcat Rubiehaven 1', 37, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (39, 'Barracuda South Yasmine 1', 38, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (40, 'Dugong South Lorenzotown 1', 39, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (41, 'Dinosaur Billchester 1', 40, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (42, 'Baboon West Fayeton 1', 41, 6);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (43, 'Antelope East Valentine 1', 42, 6);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (44, 'Hare Rocheland 1', 43, 6);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (45, 'Capybara Lake Chelseaview 1', 44, 6);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (46, 'Lemur Humbertotown 1', 45, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (47, 'Kouprey Roberttown 1', 46, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (48, 'Turkey South Ashly 1', 47, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (49, 'Panther Dumontside 1', 48, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (50, 'Reindeer Lake Lauren', 49, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (51, 'Red panda North Myriamland 1', 50, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (52, 'Pheasant East Rodrigoside 1', 51, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (53, 'Termite Chevalierberg 2', 1, 1);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (97, 'Lemur Humbertotown 2', 45, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (67, 'Lyrebird Lake Dorianfort 2', 15, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (99, 'Turkey South Ashly 2', 47, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (94, 'Antelope East Valentine 2', 42, 6);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (80, 'Woodcock Isaiahside 2', 28, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (92, 'Dinosaur Billchester 2', 40, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (64, 'Rook Port Jaimefort 2', 12, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (58, 'Eel Lake Zachery 2', 6, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (96, 'Capybara Lake Chelseaview 2', 44, 6);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (103, 'Pheasant East Rodrigoside 2', 51, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (87, 'Ram North Oscar 2', 35, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (81, 'Goshawk East Rosella 2', 29, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (63, 'Chough East Alf 2', 11, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (66, 'Crane North Nelda 2', 14, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (101, 'Reindeer Lake Lauren 2', 49, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (69, 'Swallow Garryshire 2', 17, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (68, 'Sand Dollar Lillianchester 2', 16, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (98, 'Kouprey Roberttown 2', 46, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (56, 'Sparrow South Matilde 2', 4, 1);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (57, 'Hummingbird North Mckaylamouth 2', 5, 1);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (74, 'Parrot West Sylvester 2', 22, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (76, 'Peafowl Fabrebury 2', 24, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (89, 'Wildcat Rubiehaven 2', 37, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (72, 'Hippopotamus Port Stephanymouth 2', 20, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (71, 'Goat Lake Ashley 2', 19, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (95, 'Hare Rocheland 2', 43, 6);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (86, 'Barracuda Renaudton 2', 34, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (91, 'Dugong South Lorenzotown 2', 39, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (73, 'Chicken Domenicaland 2', 21, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (75, 'Llama Lamberthaven 2', 23, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (61, 'Ant North Brooksbury 2', 9, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (60, 'Meerkat New Audreanneville 2', 8, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (79, 'Turkey West Billiefurt 2', 27, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (54, 'Seahorse North Tracetown 2', 2, 1);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (84, 'Capybara West Hopeland 2', 32, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (78, 'Woodpecker Dumontchester 2', 26, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (102, 'Red panda North Myriamland 2', 50, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (88, 'Lapwing New Brooklyn 2', 36, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (90, 'Barracuda South Yasmine 2', 38, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (70, 'Louse Hellenville 2', 18, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (82, 'Porcupine West Bulahchester 2', 30, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (59, 'Sand Dollar Port Zionmouth 2', 7, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (77, 'Giraffe Lake Ernesto 2', 25, 4);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (100, 'Panther Dumontside 2', 48, 7);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (62, 'Coyote Karleystad 2', 10, 2);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (93, 'Baboon West Fayeton 2', 41, 6);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (55, 'Bat Aliyahport 2', 3, 1);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (83, 'Hamster North Augustine 2', 31, 5);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (65, 'Cheetah Morinshire 2', 13, 3);
INSERT INTO public.team (id, name, clubid, leagueid) VALUES (85, 'Nightingale Port Fionaton 2', 33, 5);