insert into public.club (id, name, sportid)
values  (1, 'Termite Chevalierberg', 6),
        (2, 'Seahorse North Tracetown', 5),
        (3, 'Bat Aliyahport', 2),
        (4, 'Sparrow South Matilde', 3),
        (5, 'Hummingbird North Mckaylamouth', 4),
        (6, 'Eel Lake Zachery', 3),
        (7, 'Sand Dollar Port Zionmouth', 5),
        (8, 'Meerkat New Audreanneville', 3),
        (9, 'Ant North Brooksbury', 6),
        (10, 'Coyote Karleystad', 1),
        (11, 'Chough East Alf', 4),
        (12, 'Rook Port Jaimefort', 4),
        (13, 'Cheetah Morinshire', 7),
        (14, 'Crane North Nelda', 5),
        (15, 'Lyrebird Lake Dorianfort', 4),
        (16, 'Sand Dollar Lillianchester', 2),
        (17, 'Swallow Garryshire', 3),
        (18, 'Louse Hellenville', 5),
        (19, 'Goat Lake Ashley', 2),
        (20, 'Hippopotamus Port Stephanymouth', 5),
        (21, 'Chicken Domenicaland', 5),
        (22, 'Parrot West Sylvester', 3),
        (23, 'Llama Lamberthaven', 5),
        (24, 'Peafowl Fabrebury', 2),
        (25, 'Giraffe Lake Ernesto', 2),
        (26, 'Woodpecker Dumontchester', 1),
        (27, 'Turkey West Billiefurt', 3),
        (28, 'Woodcock Isaiahside', 7),
        (29, 'Goshawk East Rosella', 5),
        (30, 'Porcupine West Bulahchester', 1),
        (31, 'Hamster North Augustine', 3),
        (32, 'Capybara West Hopeland', 6),
        (33, 'Nightingale Port Fionaton', 5),
        (34, 'Barracuda Renaudton', 4),
        (35, 'Ram North Oscar', 4),
        (36, 'Lapwing New Brooklyn', 2),
        (37, 'Wildcat Rubiehaven', 1),
        (38, 'Barracuda South Yasmine', 6),
        (39, 'Dugong South Lorenzotown', 6),
        (40, 'Dinosaur Billchester', 7),
        (41, 'Baboon West Fayeton', 2),
        (42, 'Antelope East Valentine', 7),
        (43, 'Hare Rocheland', 3),
        (44, 'Capybara Lake Chelseaview', 6),
        (45, 'Lemur Humbertotown', 5),
        (46, 'Kouprey Roberttown', 7),
        (47, 'Turkey South Ashly', 5),
        (48, 'Panther Dumontside', 7),
        (49, 'Reindeer Lake Lauren', 4),
        (50, 'Red panda North Myriamland', 5),
        (51, 'Pheasant East Rodrigoside', 5);