insert into public.league (id, level, gender, federationid)
values  (3, 'Liga Invernal Veracruzana', 'F', 1),
        (4, 'Arizona Fall League', 'F', 2),
        (1, 'Major League', 'M', 3),
        (2, 'China National', 'M', 4),
        (5, 'National League', 'M', 5),
        (6, 'Slovak Extraliga', 'M', 6),
        (7, 'Damettan', 'F', 7),
        (8, 'Chinese New Alliance', 'M', 8),
        (13, 'Ghetto Discrict', 'M', 5),
        (9, 'Liga Pilipinas', 'F', 1),
        (12, 'National Alliance League', 'M', 4),
        (16, 'Kianaland Distric', 'F', 8),
        (19, 'Joementum League', 'M', 3),
        (18, 'Bumbledom Official', 'M', 2),
        (17, 'Japan United ', 'M', 1),
        (15, 'Victorian League', 'F', 7),
        (11, 'NBL League', 'M', 3),
        (14, 'Eastern Pro League', 'M', 6),
        (10, 'MNBL', 'F', 2);